# Do not run as a daemon so Docker can monitor the process
no-daemon

# Enable Long-Term Credential Mechanism for WebRTC
lt-cred-mech
user=myuser:mypassword
realm=railway.internal

# Tell Coturn to use TCP/TLS proxies safely
no-udp
no-udp-relay
no-tls
no-dtls

# Visual fingerprint verification for WebRTC
fingerprint
